# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish PHP82 Hyperf Base Docker image

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v3
        with:
          target: base
          tags: vladitot/php82-hyperf-base:latest,vladitot/php82-hyperf-base:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
          context: php82-hyperf
          file: ./php82-hyperf/Dockerfile
          cache-to: type=registry,ref=vladitot/php82-hyperf-base-cache
          cache-from: type=registry,ref=vladitot/php82-hyperf-base-cache
          push: true